# Generated by Django 5.0.6 on 2024-06-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_company_country_alter_company_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
